export component MainWindow inherits Window {
    height: 240px;
    title: "";
    width: 320px;
    x: 0px;
    y: 0px;
    Rectangle {
        color: #f7e790;
        height: 240px;
        width: 320px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "SourceHanSans-Medium";
        font-size: 20px;
        height: 58px;
        horizontal-alignment: center;
        text: "Example1\n";
        vertical-alignment: center;
        width: 160px;
        x: 50px;
        y: 80px;
    }
}
