export component MainWindow inherits Window {
    height: 240px;
    title: "";
    width: 320px;
    x: 0px;
    y: 0px;
    Rectangle {
        color: #8fc5f3;
        height: 240px;
        width: 320px;
        x: 0px;
        y: 0px;
    }
    Path {
        fill: #5a6f0e;
        fill-rule: evenodd;
        height: 114px;
        opacity: 0.368627;
        stroke: #e5fc14;
        stroke-width: 17px;
        width: 153px;
        x: 54px;
        y: 65px;
        MoveTo {
            x: 77;
            y: 11;
        }
        CubicTo {
            control-1-x: 77;
            control-1-y: 11;
            control-2-x: 129;
            control-2-y: 30;
            x: 129;
            y: 30;
        }
        CubicTo {
            control-1-x: 129;
            control-1-y: 30;
            control-2-x: 142;
            control-2-y: 71;
            x: 142;
            y: 71;
        }
        CubicTo {
            control-1-x: 142;
            control-1-y: 71;
            control-2-x: 105;
            control-2-y: 104;
            x: 105;
            y: 104;
        }
        CubicTo {
            control-1-x: 105;
            control-1-y: 104;
            control-2-x: 47;
            control-2-y: 104;
            x: 47;
            y: 104;
        }
        CubicTo {
            control-1-x: 47;
            control-1-y: 104;
            control-2-x: 11;
            control-2-y: 71;
            x: 11;
            y: 71;
        }
        CubicTo {
            control-1-x: 11;
            control-1-y: 71;
            control-2-x: 24;
            control-2-y: 29;
            x: 24;
            y: 29;
        }
        CubicTo {
            control-1-x: 24;
            control-1-y: 29;
            control-2-x: 77;
            control-2-y: 11;
            x: 77;
            y: 11;
        }
    }
    Path {
        fill: #5a6f0e;
        fill-rule: evenodd;
        height: 95px;
        opacity: 0.368627;
        stroke: transparent;
        stroke-width: 1px;
        width: 133px;
        x: 170px;
        y: 75px;
        MoveTo {
            x: 66;
            y: 1;
        }
        CubicTo {
            control-1-x: 66;
            control-1-y: 1;
            control-2-x: 119;
            control-2-y: 19;
            x: 119;
            y: 19;
        }
        CubicTo {
            control-1-x: 119;
            control-1-y: 19;
            control-2-x: 132;
            control-2-y: 61;
            x: 132;
            y: 61;
        }
        CubicTo {
            control-1-x: 132;
            control-1-y: 61;
            control-2-x: 96;
            control-2-y: 94;
            x: 96;
            y: 94;
        }
        CubicTo {
            control-1-x: 96;
            control-1-y: 94;
            control-2-x: 37;
            control-2-y: 94;
            x: 37;
            y: 94;
        }
        CubicTo {
            control-1-x: 37;
            control-1-y: 94;
            control-2-x: 1;
            control-2-y: 61;
            x: 1;
            y: 61;
        }
        CubicTo {
            control-1-x: 1;
            control-1-y: 61;
            control-2-x: 14;
            control-2-y: 19;
            x: 14;
            y: 19;
        }
        CubicTo {
            control-1-x: 14;
            control-1-y: 19;
            control-2-x: 66;
            control-2-y: 1;
            x: 66;
            y: 1;
        }
    }
}
