export component MainWindow inherits Window {
    height: 240px;
    title: "";
    width: 320px;
    x: 0px;
    y: 0px;
    Rectangle {
        color: #f9cff4;
        height: 240px;
        width: 320px;
        x: 0px;
        y: 0px;
    }
    Image {
        height: 46px;
        image-fit: contain;
        source: @image-url("images/qtquick.png");
        width: 64px;
        x: 40px;
        y: 80px;
    }
    Image {
        height: 48px;
        image-fit: contain;
        source: @image-url("images/qtquick_1.png");
        width: 36px;
        x: 58px;
        y: 16px;
    }
    Image {
        height: 46px;
        image-fit: contain;
        source: @image-url("images/7c7c45584dc3695d1d67a26219dfced93dd2c180e564f292def583b27ba9ecbd.png");
        width: 64px;
        x: 40px;
        y: 150px;
    }
    Image {
        height: 48px;
        image-fit: contain;
        source: @image-url("images/slint.png");
        width: 36px;
        x: 150px;
        y: 79px;
    }
    Image {
        height: 48px;
        image-fit: contain;
        source: @image-url("images/55f66e81a5e64db810dddb2ca1ea18b8f4b08b1d3946916d5e5a78e453772487.png");
        width: 36px;
        x: 150px;
        y: 149px;
    }
    Image {
        height: 40px;
        image-fit: contain;
        source: @image-url("images/flutter.png");
        width: 32px;
        x: 240px;
        y: 82px;
    }
    Image {
        height: 40px;
        image-fit: contain;
        source: @image-url("images/flutter_pixeled.png");
        width: 32px;
        x: 240px;
        y: 152px;
    }
}
