export component MainWindow inherits Window {
    height: 240px;
    title: "";
    width: 320px;
    x: 0px;
    y: 0px;
    Rectangle {
        color: #8fc5f3;
        height: 240px;
        width: 320px;
        x: 0px;
        y: 0px;
    }
    Path {
        fill: #5a6f0e;
        fill-rule: evenodd;
        height: 96px;
        opacity: 0.368627;
        stroke: transparent;
        stroke-width: 1px;
        width: 134px;
        x: 64px;
        y: 74px;
        MoveTo {
            x: 66;
            y: 2;
        }
        CubicTo {
            control-1-x: 66;
            control-1-y: 2;
            control-2-x: 119;
            control-2-y: 20;
            x: 119;
            y: 20;
        }
        CubicTo {
            control-1-x: 119;
            control-1-y: 20;
            control-2-x: 132;
            control-2-y: 62;
            x: 132;
            y: 62;
        }
        CubicTo {
            control-1-x: 132;
            control-1-y: 62;
            control-2-x: 96;
            control-2-y: 95;
            x: 96;
            y: 95;
        }
        CubicTo {
            control-1-x: 96;
            control-1-y: 95;
            control-2-x: 37;
            control-2-y: 95;
            x: 37;
            y: 95;
        }
        CubicTo {
            control-1-x: 37;
            control-1-y: 95;
            control-2-x: 1;
            control-2-y: 62;
            x: 1;
            y: 62;
        }
        CubicTo {
            control-1-x: 1;
            control-1-y: 62;
            control-2-x: 14;
            control-2-y: 20;
            x: 14;
            y: 20;
        }
        CubicTo {
            control-1-x: 14;
            control-1-y: 20;
            control-2-x: 66;
            control-2-y: 2;
            x: 66;
            y: 2;
        }
    }
}
