export component MainWindow inherits Window {
    height: 240px;
    title: "";
    width: 320px;
    x: 0px;
    y: 0px;
    Rectangle {
        color: #f7e790;
        height: 240px;
        width: 320px;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 52px;
        width: 182px;
        x: 39px;
        y: 49px;
        Rectangle {
            background: #d4f5c9;
            border-radius: 20px;
            height: 50px;
            width: 180px;
            x: 1px;
            y: 1px;
        }
    }
    Rectangle {
        height: 13px;
        width: 139px;
        x: 72px;
        y: 89px;
        Rectangle {
            background: #217903;
            height: 10px;
            width: 137px;
            x: 1px;
            y: 1px;
        }
    }
    Rectangle {
        height: 14px;
        width: 25px;
        x: 79px;
        y: 81px;
        Rectangle {
            background: #5e88e7;
            height: 12px;
            width: 23px;
            x: 1px;
            y: 1px;
        }
    }
    Text {
        color: #000000;
        font-family: "SourceHanSans-Medium";
        font-size: 20px;
        height: 58px;
        horizontal-alignment: center;
        text: "Example1";
        vertical-alignment: center;
        width: 160px;
        x: 50px;
        y: 63px;
    }
    Rectangle {
        height: 52px;
        width: 182px;
        x: 39px;
        y: 134px;
        Rectangle {
            background: #d4f5c9;
            border-radius: 20px;
            height: 50px;
            width: 180px;
            x: 1px;
            y: 1px;
        }
    }
    Rectangle {
        height: 12px;
        width: 139px;
        x: 72px;
        y: 174px;
        Rectangle {
            background: #217903;
            height: 10px;
            width: 137px;
            x: 1px;
            y: 1px;
        }
    }
    Rectangle {
        height: 14px;
        width: 25px;
        x: 179px;
        y: 166px;
        Rectangle {
            background: #5e88e7;
            height: 12px;
            width: 23px;
            x: 1px;
            y: 1px;
        }
    }
    Text {
        color: #000000;
        font-family: "SourceHanSans-Medium";
        font-size: 20px;
        height: 58px;
        horizontal-alignment: center;
        text: "Example1";
        vertical-alignment: center;
        width: 160px;
        x: 50px;
        y: 143px;
    }
}
