export component MainWindow inherits Window {
    height: 240px;
    title: "";
    width: 320px;
    x: 0px;
    y: 0px;
    Rectangle {
        color: #1b868a;
        height: 240px;
        width: 320px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #000000;
        font-family: "源ノ角ゴシック JP";
        font-size: 50px;
        horizontal-alignment: center;
        text: "";
        vertical-alignment: center;
        x: 0px;
        y: 0px;
    }
    Rectangle {
        height: 100px;
        width: 242px;
        x: 29px;
        y: 19px;
        Rectangle {
            background: #a8f6ed;
            height: 97px;
            width: 240px;
            x: 1px;
            y: 1px;
        }
    }
    Rectangle {
        height: 52px;
        width: 242px;
        x: 29px;
        y: 19px;
        Rectangle {
            background: #7f64f6;
            height: 50px;
            width: 240px;
            x: 1px;
            y: 1px;
        }
    }
    Text {
        color: #000000;
        font-family: "源ノ角ゴシック JP";
        font-size: 50px;
        height: 96px;
        horizontal-alignment: center;
        text: "shooting";
        vertical-alignment: center;
        width: 239px;
        x: 30px;
        y: 20px;
    }
}
