export component MainWindow inherits Window {
    height: 240px;
    title: "";
    width: 640px;
    x: 0px;
    y: 0px;
    Rectangle {
        color: #012401;
        height: 240px;
        width: 640px;
        x: 0px;
        y: 0px;
    }
    Text {
        color: #ffffff;
        font-family: "源ノ角ゴシック JP";
        font-size: 50px;
        height: 70px;
        horizontal-alignment: center;
        text: "12pt";
        vertical-alignment: center;
        width: 120px;
        x: 30px;
        y: 30px;
    }
    Text {
        color: #ffffff;
        font-family: "源ノ角ゴシック JP";
        font-size: 150px;
        height: 211px;
        horizontal-alignment: center;
        text: "150px";
        vertical-alignment: center;
        width: 478px;
        x: 150px;
        y: 60px;
    }
}
